import type { Metadata } from "next"
import "./global.scss"

export const metadata: Metadata = {
    title: "JS-Terminal",
    description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en"> 
            <body suppressHydrationWarning={true}>
                {children}
            </body>
        </html>
    )
}